### ISSUE TITLE
[frontend][web] UserQuery not work correctly

### ISSUE THREAD

**Issue by wgbn** [Tech4covid19/trackovid19-web#110]
Com podes ver, em em **isolation-status.component.ts** os seguintes métodos retornam sem undefined
```
const id = this.query.getActiveId();
const user = this.query.getEntity(id);
```
Não sou conhecedor do uso de _flux/redux/graphql_, por isso peço auxílio com esta issue.
Deve verificar também se as outras queries da pasta **States** tambem estão a aptresentar problemas.

**Comment by fabioscsilva** [comment]
closing, since this was fixed in other PR.
