### ISSUE TITLE
[frontend][web] send to api the user opt-in actions from terms and conditions screen

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#183]

**Comment by fernanri** [comment]
Opt-ins can be sent when updating the user details (PUT on /user). 
A sample payload is:

`{
    "postalCode": "4200-192",
    "geo": {
    	"lat": 10.34,
    	"lon": 2.8
    },
    "phone": "+351960123122",
    "email": "jane@doe.com",
    "name": "Jane Doe",
    "patientToken": "QWERTY",
    "showOnboarding": false,
    "optin_download_use": true,
    "optin_privacy": true,
    "optin_health_geo": true,
    "optin_push": true
}`

**Comment by wgbn** [comment]
solved #192
