### ISSUE TITLE
[frontend][web] mobile ios + chrome, the user cannot read the full privacy policy

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#206]
https://tech4covid19.slack.com/files/U0102KDDDL6/F010KQYSW6Q/rpreplay_final1584989537.mp4

<img width="424" alt="77355233-035b4580-6d3c-11ea-98d2-b011c0300b05" src="https://user-images.githubusercontent.com/1127990/77360624-9c428e80-6d45-11ea-8809-be399e159e5f.png">

**Comment by wgbn** [comment]
A solução é remover? A ideia de abrir um modal foi para evitar ficar abrindo novas janelas, preferem mesmo ficar a abrir novas janelas?

**Comment by lcfb91** [comment]
Parece que sem modal fica mais legivel principalmente em mobile, nesse sentido abrimos uma nova janela neste caso especifico dos termos e condições
