### ISSUE TITLE
privacy notice does not scroll on mobie

### ISSUE THREAD

**Issue by skyhorse** [Tech4covid19/trackovid19-web#208]
<img width="424" alt="Screenshot 2020-03-23 at 19 14 36" src="https://user-images.githubusercontent.com/930491/77355233-035b4580-6d3c-11ea-98d2-b011c0300b05.png">

Can't scroll down past the visible text.

iOS + Chrome mobile

**Comment by fabioscsilva** [comment]
Closing this one, since is duplicated with #206
