### ISSUE TITLE
[frontend][web] enable push notifications

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#242]
related https://github.com/Tech4covid19/trackovid19-backend/issues/101

**Comment by pfortuna** [comment]
Vai desenhar um sticky bar que aparece 5 segundos depois do Dashboard ser mostrado na primeira vez depois do registo. Essa sticky bar vai permitir aceitar o envio de notificações ou recusar. A resposta é metida num cookie. Havendo este cookie a bar não aparece. 

Se disser que sim, faz subscribe no backend.
