### ISSUE TITLE
[frontend][web] call endpoint for deleting user account instead of sending email

### ISSUE THREAD

**Issue by fernanri** [Tech4covid19/trackovid19-web#251]
As soon as the delete user account endpoint is available one should call it instead of sending an email.

**Comment by fernanri** [comment]
When clicking the link one should:

1. Show a dialog window to confirm data erasure request, namely stating it is not undoable and user will receive confirmation email once done

**Comment by pfortuna** [comment]
Requires https://github.com/Tech4covid19/trackovid19-backend/issues/109

We need UXUI for the dialog window @geiras

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/77837070-3181c080-7154-11ea-83b4-90c13e177c15.png)

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/77837345-a7d3f200-7157-11ea-98e9-fc9a84af48ac.png)

**Comment by geiras** [comment]
https://drive.google.com/file/d/1grBVQB4fvZqsEyiB0q5j3aqQTdc8zAF1/view

**Comment by nunofgm** [comment]
I'll be doing the frontend part while the backend is also in progress.

One question @pfortuna, what happens after the delete? The user will be redirected to the landing page? Some success/failure feedback will appear? Thanks

**Comment by pfortuna** [comment]
The user is redirected to the landing page (not login page). 
The plan was also to send him an email, but this decision was reverted.
Please delete the last sentence.

You need to call this endpoint.
https://github.com/Tech4covid19/trackovid19-backend/issues/109

You'll receive this if everything went ok, or false if not.
{
"success": true
}

@geiras how can we communicate to the user that the account deletion was completed successfully (or otherwise if it didn't) ?

**Comment by geiras** [comment]
> The user is redirected to the landing page (not login page).
> The plan was also to send him an email, but this decision was reversed.
> Please delete the last sentence.
> 
> You need to call this endpoint.
> [Tech4covid19/trackovid19-backend#109](https://github.com/Tech4covid19/trackovid19-backend/issues/109)
> 
> You'll receive this if everything went ok, or false if not.
> {
> "success": true
> }
> 
> @geiras how can we communicate to the user that the account deletion was completed successfully (or otherwise if it didn't)?

Yes, we can. What would be the option to when the account deletion was not completed successfully?

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/78068372-359a2200-7390-11ea-8d1c-2d5a2b901900.png)

**Comment by pfortuna** [comment]
This works well! 
"problem" => "problema"

**Comment by pfortuna** [comment]
@nunofgm the endpoint already exists, we need this dialog for confirming. The dialog is similar to other dialogs we have.

**Comment by nunofgm** [comment]
@pfortuna I’m already working on that. I suppose it's okay to delete and re-create the test account I have, right?

**Comment by nunofgm** [comment]
The endpoint is returning 
`{ status: "ok" }`

instead of 

`{ success: "true"}`

Can I go with it @pfortuna ?

**Comment by pfortuna** [comment]
Yes, it's not a big issue as long as you deal with that difference. 
The PR can be accepted.
