### ISSUE TITLE
[frontend][web] the website does not open with ublock installed

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#256]
chrome > macos catalina

**Comment by diogoteix** [comment]
I think this was because of the Facebook script being blocked, which would cause that FB.init error.
That error is fixed, so it should be working but, when that script is blocked, we can't share to facebook

**Comment by pfortuna** [comment]
@ruicosta-codavel said its working fine, and he uses ublock.
Closing
