### ISSUE TITLE
[frontend][web] quando se preenche automaticamente o código postal, ele preenche o código covidografia mais abaixo

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#261]

**Comment by pfortuna** [comment]
Is this still happening?

**Comment by pfortuna** [comment]
@lcfb91 is this still happening?

**Comment by fabioscsilva** [comment]
In this one we could disable autocomplete or add tips to the browsers like `bday-year` and `postal-code`. 
@lcfb91 @pfortuna Which option you prefer?

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by pfortuna** [comment]
Probably simpler to disable autocomplete, since it's such a small form.
