### ISSUE TITLE
[frontend][web] Optimize share buttons ruler

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#274]
Reorder sharing buttons to:
1- Facebook
2- Whatsapp
3- Facebook messenger
4- Linkedin
5- Twitter
6- Copy link+text/copy

Add the ones that do not exist yet.

**Comment by pfortuna** [comment]
- ToDo: insert figma link here after UX design

**Comment by geiras** [comment]
[https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3114%3A0](url)

**Comment by geiras** [comment]
[https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3114%3A0](Figma Share Buttons)

Since we added more buttons, we need to add support to horizontal scroll.

**Comment by geiras** [comment]
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3114%3A0
Since we added more buttons, we need to add support to horizontal scroll.

**Comment by ruijadom** [comment]
@pfortuna for the facebook-messenger sharing there is any config info in facebook API  acccount?
