### ISSUE TITLE
[frontend][landing] Create a "Perguntas Frequentes" page

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#275]
The copy is in the google drive document:
CovidografiaPerguntasFrequentes(FAQ)

**Comment by geiras** [comment]
Since I'm waiting for content for the FAQ page, I worked on the menu instead. 
![image](https://user-images.githubusercontent.com/22840903/77838067-233d9f80-7168-11ea-89b1-f9e8cacdcc85.png)

Example of how we could tidy all the options accessible through the dashboard.

**Comment by pfortuna** [comment]
This is not the correct issue. I'll create one right now.

**Comment by pfortuna** [comment]
@geiras see issue #316 please.

**Comment by geiras** [comment]
DESKTOP:

![image](https://user-images.githubusercontent.com/22840903/78500905-27158700-7751-11ea-947f-3c0cbdbd790c.png)

Figma:
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3974%3A6982

All the text, hyperlinks and full content can be found in this document:
https://docs.google.com/document/d/17yZLPBsXqgpQYwu49nzGlqz8eQ-1xPYEY1sXZcz9KN8/edit#

Any doubts, tag me or send me a PM over Slack.

Mobile version coming soon.

**Comment by geiras** [comment]
Final copy and hyperlinks can be found on this document:
https://docs.google.com/document/d/17yZLPBsXqgpQYwu49nzGlqz8eQ-1xPYEY1sXZcz9KN8/edit?usp=sharing
