### ISSUE TITLE
When updating status, if we press refresh on step 2 or 3, it becomes impossible to move forward

### ISSUE THREAD

**Issue by tiruicosta** [Tech4covid19/trackovid19-web#278]
<img width="1440" alt="Screenshot 2020-03-26 at 20 19 42" src="https://user-images.githubusercontent.com/62185464/77692773-23d70a00-6f9f-11ea-8cbe-b826e6493d7b.png">

**Comment by pfortuna** [comment]
- if the user refreshes browser or clicks back button, forget everything and start from step 1

**Comment by pfortuna** [comment]
Duplicate #215
