### ISSUE TITLE
[frontend][web] Only use one package manager and lock all dependencies versions

### ISSUE THREAD

**Issue by ruisaraiva19** [Tech4covid19/trackovid19-web#281]
At the moment, the project has both `package-lock.json` and `yarn.lock` files.

It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.

Also pretty much all dependencies on the `package.json` file aren't locked. We should pin all dependencies versions in order to get packages resolution consistency for everyone (developers, CI environments, etc).

**Comment by ruisaraiva19** [comment]
@diogoteix @fabioscsilva can I get your opinion on which package manager to use going forward (NPM or Yarn)?

**Comment by fabioscsilva** [comment]
I'm ok with both, but usually I use NPM.

**Comment by pfortuna** [comment]
+1 package-lock.json

**Comment by ruisaraiva19** [comment]
I also agree with `package-lock.json`.
I'll remove the `yarn.lock` then.
