### ISSUE TITLE
[frontend] Force status update after login in some situations

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#284]
When the user logs in, we need to:
- check if the last status was > 24h before (use the table that has full time precision). 
- if true, force the user to submit a status update and only after that we give him access to the dashboard
- if false, show him the dashboard

**Comment by pfortuna** [comment]
Requires https://github.com/Tech4covid19/trackovid19-backend/issues/120

**Comment by pfortuna** [comment]
Hey guys, how did you implement this without this:
https://github.com/Tech4covid19/trackovid19-backend/issues/120

Can't remember in which issue I asked for it, but we also need to remove the property "cases" from /api/v1/user. 

Can you clarify please?

**Comment by nunofgm** [comment]
@pfortuna with the property ‘update_at’ . It’s not the correct one?

**Comment by pfortuna** [comment]
No. That property is used to keep a timestamp last time a particular user data was updated, but not to hold the last time a status update was received. Two different updates. 

You should specifically read this property:
Requires Tech4covid19/trackovid19-backend#120

Can you refactor this please?
Also, someone needs to implemente the above issue as well.

**Comment by pfortuna** [comment]
Moving this to In progress...

**Comment by nunofgm** [comment]
@pfortuna sure. I'll comment the redirect until the [#120](https://github.com/Tech4covid19/trackovid19-backend/issues/120) is done

**Comment by nunofgm** [comment]
@pfortuna Revert: https://github.com/Tech4covid19/trackovid19-web/pull/311
