### ISSUE TITLE
[frontend][web] the ability to cancel a status udpate

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#286]
We should have a way to cancel a status update. Perhaps a X button in the top right.

**Comment by pfortuna** [comment]
@geiras this is done, isn't it? can you please copy the URL here so that I can move it to TODO?

**Comment by geiras** [comment]
MOBILE
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3124%3A6

DESKTOP
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3353%3A384

**Comment by pfortuna** [comment]
@jjamaral how is this? are you close to an PR? we need this for next monday release.

**Comment by pfortuna** [comment]
Pull request #342 submitted by @nunofgm

**Comment by jjamaral** [comment]
Yeah, I was working on this but we had our dev environment with some issues and I couldn't finish.
It's done, good job!
