### ISSUE TITLE
[frontend][web] Implement Google Oauth2 login

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#298]
Implement the frontend side of Google Oauth2 login

Requires #297
Requires https://github.com/Tech4covid19/trackovid19-backend/issues/128

**Comment by geiras** [comment]
![image](https://user-images.githubusercontent.com/22840903/77837691-fedfc400-7163-11ea-9501-aa22925044d7.png)

**Mobile**
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3394%3A154

**Desktop**
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Covidografia?node-id=3394%3A156

**Comment by geiras** [comment]
Since Google states the primary button as white, I added a slight shade to the background to make it a little more visible.

**Comment by pfortuna** [comment]
![Screenshot 2020-04-04 at 22 56 23](https://user-images.githubusercontent.com/5217265/78462212-de65bb80-76c7-11ea-9417-b6330c77d7ee.png)

It's not working here. Also tested in incognito. Same result.
