### ISSUE TITLE
[frontend][web] Add Angular service worker support

### ISSUE THREAD

**Issue by ruisaraiva19** [Tech4covid19/trackovid19-web#304]
https://angular.io/guide/service-worker-getting-started

**Comment by fabioscsilva** [comment]
hi @ruisaraiva19, can you explain the idea behind this issue? I'm following you, this is probably already made on this PR #305

**Comment by ruisaraiva19** [comment]
> hi @ruisaraiva19, can you explain the idea behind this issue? I'm following you, this is probably already made on this PR #305

Hi @fabioscsilva, you're right. The idea was to add a service worker, icons and meta tags to index.html.
The #305 PR has this already or at least the base work 😉.
I'll do a code review now 👌.

**Comment by pfortuna** [comment]
Should we close this?

**Comment by ruisaraiva19** [comment]
Yes, we can close this.
