### ISSUE TITLE
[frontend] For old registered users, we must show the popup for subscribing push notifications

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#310]
User accounts older than the moment we released push notifications after they login, they should see the push notifications subscription modal.

We should reuse the same code we develop before.

**Comment by fabioscsilva** [comment]
@pfortuna Right now (in staging), every time we close the share-modal, we are checking if the user has already subscribed the push notifications and if not, we show the subscribe banner. Is this enough or are you thinking in something different?

**Comment by pfortuna** [comment]
Well, that might be slightly nagging as they will see it every time they do a status update. 
If you say No once, you shouldn't have to answer to that question over and over.

One way of implementing this, is setting a cookie to store the answer. If he says no, then set a cookie with "no" (must not have the flag http_only set). If he wants to reenable, then he'll have a menu option for that later on.

**Comment by fabioscsilva** [comment]
👍 Sounds good! I was just checking if the user granted the access or not, and if not, annoying him with it again.

I will improve it with your suggestion.

**Comment by fabioscsilva** [comment]
Improving this, is the purpose  of this issue covered with flow that I described?

**Comment by pfortuna** [comment]
Yes, this solves the issue.
