### ISSUE TITLE
[frontend] Update copy with respect to “Rotina Habitual”

### ISSUE THREAD

**Issue by tiruicosta** [Tech4covid19/trackovid19-web#312]
- In status update, instead of “Faço a minha rotina habitual” use **“Trabalho fora de casa”**
- In the dashboard, instead of “Rotina habitual” use **“A trabalhar fora de casa”**
- In the status update, instead of “Presumo estar saudável e estou por opção em casa em prevenção” use **“Presumo estar saudável e, por prevenção, estou em casa”**

**Comment by pfortuna** [comment]
Some of these changes require changing the .sql files.
Also, we don't have a db migration so we also need to perform manual UPDATES in staging and production. Please contact me for this part.

**Comment by diogoteix** [comment]
@pfortuna I will do the frontend part. Is there already a backend issue for the rest?
Just to make sure this doesn't get lost

**Comment by pfortuna** [comment]
We didn't, but we now have one:
https://github.com/Tech4covid19/trackovid19-backend/issues/146

Please do the frontend part of it.

Thanks
