### ISSUE TITLE
[frontend][web] service worker should only deal with push notifications

### ISSUE THREAD

**Issue by carlospombeiro** [Tech4covid19/trackovid19-web#315]
Service worker is doing many things but should only deal with push notifications.
The "offline" functionality is causing issues in the requests to the api.

**Comment by fabioscsilva** [comment]
@carlospombeiro Why this is an issue? If we want a PWA, like we talked we need this.

> The "offline" functionality is causing issues in the requests to the api.

Can you give more details about this?

**Comment by carlospombeiro** [comment]
@fabioscsilva  we have some issues after the deploy to staging. Let's put this on hold for now and check it again when the backend is ok.

**Comment by pfortuna** [comment]
How is it now?

**Comment by fabioscsilva** [comment]
@carlospombeiro @pfortuna
By the info that we have know, the problem on staging wasn't related with the service worker, right?

Taking this in account and the fact that we want to go with a PWA, our service worker needs to do more than just deal with push notifications. So I would suggest to close this issue.

Everyone agrees?

**Comment by pfortuna** [comment]
Nothing against it.

**Comment by carlospombeiro** [comment]
Close it!

**Comment by pfortuna** [comment]
Closed!
