### ISSUE TITLE
[frontend] Duplicated numbers in dashboard 

### ISSUE THREAD

**Issue by tiruicosta** [Tech4covid19/trackovid19-web#318]
Occurred in Android Samsung j5 (reported by user)

<img width="174" alt="Screenshot 2020-03-30 at 23 22 45" src="https://user-images.githubusercontent.com/62185464/77967697-8997fe80-72dd-11ea-9d5a-712c171bfe8f.png">

Also, utilizadores has a space: "Utilizador es"

**Comment by fabioscsilva** [comment]
@ruicosta-codavel Can you confirm with who reported this that is still happening?
It looks like a problem with the device or the browser of that user. 
I can replicate it at all.

Have you seen that event the word `utilizadores` is broken? `Utilizador es`

**Comment by fabioscsilva** [comment]
@ruicosta-codavel any update on this one?

**Comment by tiruicosta** [comment]
Sorry @fabioscsilva , missed the first comment. I was also not unable to replicate and the person who reported was not the owner of the phone (it was someone in a Whatsapp group that told him). 

If @pfortuna agrees, we should close this one.

**Comment by pfortuna** [comment]
Closed.
