### ISSUE TITLE
[frontend] After login in with Google, the loginmethod = Facebook

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-web#357]
The loginmethod is being set to Facebook after login in with Google.

The test was preceded with complete wipe of cookies and localstorage.

**Comment by tiruicosta** [comment]
We received this email:
<img width="589" alt="Screenshot 2020-04-08 at 18 32 04" src="https://user-images.githubusercontent.com/62185464/78826794-090e8780-79da-11ea-8c85-4249222601fa.png">

@pfortuna shall we reopen it?

**Comment by pfortuna** [comment]
When was this?

**Comment by tiruicosta** [comment]
Today at 1:36pm

**Comment by pfortuna** [comment]
I tested this fix and it was working. Please ask the user to clear site
data and try again.

**Comment by tiruicosta** [comment]
Will do
