### ISSUE TITLE
[frontend] prevent translate popup

### ISSUE THREAD

**Issue by carlospombeiro** [Tech4covid19/trackovid19-web#360]
Prevent browser translate popup with 
`<html translate="no">`

https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome

**Comment by carlospombeiro** [comment]
![translate](https://user-images.githubusercontent.com/4192910/78597065-be0f3b80-7844-11ea-9ef4-4d50e98d308d.png)

**Comment by fabioscsilva** [comment]
I don't see this as an issue, since we could have people in Portugal that don't know Portuguese and need to use the browser translator. What do you think @pfortuna ?

**Comment by pfortuna** [comment]
I agree with @fabioscsilva. It actually never happened to me. I'm guessing your browser doesn't know you know Portuguese...

**Comment by carlospombeiro** [comment]
I think my mac only understands english...
Ok I get the idea we didn't want this popup.
Closing the issue...

**Comment by pfortuna** [comment]
We removed the pop-up that asks if the user wants to use the latest
version. That is supposed to be in prod. Is this still happening?
Regression?
