### ISSUE TITLE
Onboarding Screen & Components

### ISSUE THREAD

**Issue by palminha** [Tech4covid19/trackovid19-web#9]
Branch: onboarding-view

TODO:
-  Scaffolding - **Done**
-  Carousel Logic - **Done**
-   Build Slider Component - **Todo**
-   Add Images - **Todo**
-   Route to homepage on last frame - **Todo**
-    @media css queries or no mobile css code - **check** 

RELATED: Detect temporal first user session to route to onboarding.

**Comment by lcfb91** [comment]
moved to https://github.com/Tech4covid19/trackovid19-web/issues/19
