### ISSUE TITLE
[frontend][web] fix the icons of dashboard

### ISSUE THREAD

**Issue by lcfb91** [Tech4covid19/trackovid19-web#96]
Icons are not being loaded correctly

**Comment by lcfb91** [comment]
![Screenshot 2020-03-20 at 11 57 35](https://user-images.githubusercontent.com/5757078/77161699-3387b780-6aa2-11ea-9cce-6ded6c75b0a3.png)

**Comment by lcfb91** [comment]
should looks like 
https://www.figma.com/file/BfK7HtPsvxZAwZLg1ebz2u/Tracovid?node-id=323%3A1120

**Comment by fabioscsilva** [comment]
[
    {
        "postalcode": "4200-192",
        "status": 1,
        "status_text": "Infetados",
        "hits": "2"
    },
    {
        "postalcode": "4200-192",
        "status": 2,
        "status_text": "Suspeitos",
        "hits": "0"
    },
    {
        "postalcode": "4200-192",
        "status": 3,
        "status_text": "Recuperados",
        "hits": "2"
    },
    {
        "postalcode": "4200-192",
        "status": 4,
        "status_text": "Não sabem",
        "hits": "1"
    },
    {
        "postalcode": "4200-192",
        "status": 200,
        "status_text": "Sem sintomas",
        "hits": "1"
    }
]
100 é "Com sintomas"

**Comment by fabioscsilva** [comment]
[
    {
        "postalcode": "4200",
        "confinement_state": 1,
        "confinement_state_text": "Em casa, preventivamente",
        "hits": "1"
    },
    {
        "postalcode": "4200",
        "confinement_state": 4,
        "confinement_state_text": "Rotina habitual",
        "hits": "1"
    },
    {
        "postalcode": "4200",
        "confinement_state": 300,
        "confinement_state_text": "Isolados",
        "hits": "2"
    }
]
